jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal
    username: root
    password: huy123huy
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  data:
    rest:
      base-path: /api
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB